// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  commodity: __t.string().primaryKey(),
  basePrice: __t.f64().name("base_price"),
  currentPrice: __t.f64().name("current_price"),
  previousPrice: __t.f64().name("previous_price"),
  priceChange: __t.f64().name("price_change"),
  priceChangePercent: __t.f64().name("price_change_percent"),
  globalSupply: __t.f64().name("global_supply"),
  globalDemand: __t.f64().name("global_demand"),
  scarcityLevel: __t.f32().name("scarcity_level"),
  recentBuyVolume: __t.f64().name("recent_buy_volume"),
  recentSellVolume: __t.f64().name("recent_sell_volume"),
  volatility: __t.f32(),
  eventMultiplier: __t.f32().name("event_multiplier"),
  crisisUntilYear: __t.f32().name("crisis_until_year"),
  lastUpdatedYear: __t.f32().name("last_updated_year"),
});
