// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  owner: __t.identity().primaryKey(),
  name: __t.string(),
  money: __t.u64(),
  education: __t.f32(),
  taxRate: __t.f32().name("tax_rate"),
  health: __t.f32(),
  military: __t.f32(),
  technology: __t.f32(),
  gdp: __t.f64(),
  bot: __t.bool(),
});
