// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  Resource,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  fromOwner: __t.identity().name("from_owner"),
  toOwner: __t.identity().name("to_owner"),
  get giveResource() {
    return Resource.name("give_resource");
  },
  giveAmount: __t.u64().name("give_amount"),
  get getResource() {
    return Resource.name("get_resource");
  },
  getAmount: __t.u64().name("get_amount"),
  createdAt: __t.timestamp().name("created_at"),
});
