// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Nation = __t.object("Nation", {
  owner: __t.identity(),
  name: __t.string(),
  money: __t.u64(),
  goods: __t.u64(),
  energy: __t.u64(),
  education: __t.f32(),
  taxRate: __t.f32(),
  health: __t.f32(),
  gdp: __t.f64(),
});
export type Nation = __Infer<typeof Nation>;

// The tagged union or sum type for the algebraic type `Resource`.
export const Resource = __t.enum("Resource", {
  Goods: __t.unit(),
  Energy: __t.unit(),
});
export type Resource = __Infer<typeof Resource>;

export const TradeOffer = __t.object("TradeOffer", {
  id: __t.u64(),
  fromOwner: __t.identity(),
  toOwner: __t.identity(),
  get giveResource() {
    return Resource;
  },
  giveAmount: __t.u64(),
  get getResource() {
    return Resource;
  },
  getAmount: __t.u64(),
  createdAt: __t.timestamp(),
});
export type TradeOffer = __Infer<typeof TradeOffer>;

export const Trust = __t.object("Trust", {
  id: __t.u64(),
  fromOwner: __t.identity(),
  toOwner: __t.identity(),
  value: __t.u8(),
});
export type Trust = __Infer<typeof Trust>;

export const World = __t.object("World", {
  id: __t.u8(),
  year: __t.f32(),
  get status() {
    return WorldStatus;
  },
});
export type World = __Infer<typeof World>;

// The tagged union or sum type for the algebraic type `WorldStatus`.
export const WorldStatus = __t.enum("WorldStatus", {
  Lobby: __t.unit(),
  Running: __t.unit(),
  Ended: __t.unit(),
});
export type WorldStatus = __Infer<typeof WorldStatus>;

