// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Nation = __t.object("Nation", {
  owner: __t.identity(),
  name: __t.string(),
  money: __t.u64(),
  goods: __t.u64(),
  energy: __t.u64(),
  education: __t.f32(),
  taxRate: __t.f32(),
});
export type Nation = __Infer<typeof Nation>;

export const World = __t.object("World", {
  id: __t.u8(),
  year: __t.f32(),
  get status() {
    return WorldStatus;
  },
});
export type World = __Infer<typeof World>;

// The tagged union or sum type for the algebraic type `WorldStatus`.
export const WorldStatus = __t.enum("WorldStatus", {
  Lobby: __t.unit(),
  Running: __t.unit(),
  Ended: __t.unit(),
});
export type WorldStatus = __Infer<typeof WorldStatus>;

