// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Asset = __t.object("Asset", {
  id: __t.u64(),
  owner: __t.identity(),
  typeKey: __t.string(),
  builtYear: __t.f32(),
});
export type Asset = __Infer<typeof Asset>;

export const CommodityMarket = __t.object("CommodityMarket", {
  commodity: __t.string(),
  basePrice: __t.f64(),
  currentPrice: __t.f64(),
  previousPrice: __t.f64(),
  priceChange: __t.f64(),
  priceChangePercent: __t.f64(),
  globalSupply: __t.f64(),
  globalDemand: __t.f64(),
  scarcityLevel: __t.f32(),
  recentBuyVolume: __t.f64(),
  recentSellVolume: __t.f64(),
  volatility: __t.f32(),
  eventMultiplier: __t.f32(),
  crisisUntilYear: __t.f32(),
  lastUpdatedYear: __t.f32(),
});
export type CommodityMarket = __Infer<typeof CommodityMarket>;

export const GdpHistory = __t.object("GdpHistory", {
  id: __t.u64(),
  owner: __t.identity(),
  year: __t.f32(),
  gdp: __t.f64(),
});
export type GdpHistory = __Infer<typeof GdpHistory>;

export const MarketHistory = __t.object("MarketHistory", {
  id: __t.u64(),
  commodity: __t.string(),
  year: __t.f32(),
  price: __t.f64(),
});
export type MarketHistory = __Infer<typeof MarketHistory>;

export const Nation = __t.object("Nation", {
  owner: __t.identity(),
  name: __t.string(),
  money: __t.u64(),
  education: __t.f32(),
  taxRate: __t.f32(),
  health: __t.f32(),
  military: __t.f32(),
  technology: __t.f32(),
  gdp: __t.f64(),
  bot: __t.bool(),
});
export type Nation = __Infer<typeof Nation>;

export const Production = __t.object("Production", {
  id: __t.u64(),
  owner: __t.identity(),
  commodity: __t.string(),
  perYear: __t.u64(),
});
export type Production = __Infer<typeof Production>;

export const Stockpile = __t.object("Stockpile", {
  id: __t.u64(),
  owner: __t.identity(),
  commodity: __t.string(),
  amount: __t.u64(),
});
export type Stockpile = __Infer<typeof Stockpile>;

export const TradeOffer = __t.object("TradeOffer", {
  id: __t.u64(),
  fromOwner: __t.identity(),
  toOwner: __t.identity(),
  giveCommodity: __t.string(),
  giveAmount: __t.u64(),
  getCommodity: __t.string(),
  getAmount: __t.u64(),
  createdAt: __t.timestamp(),
});
export type TradeOffer = __Infer<typeof TradeOffer>;

export const Trust = __t.object("Trust", {
  id: __t.u64(),
  fromOwner: __t.identity(),
  toOwner: __t.identity(),
  value: __t.u8(),
});
export type Trust = __Infer<typeof Trust>;

export const War = __t.object("War", {
  id: __t.u64(),
  attacker: __t.identity(),
  defender: __t.identity(),
  startYear: __t.f32(),
  active: __t.bool(),
});
export type War = __Infer<typeof War>;

export const World = __t.object("World", {
  id: __t.u8(),
  year: __t.f32(),
  get status() {
    return WorldStatus;
  },
});
export type World = __Infer<typeof World>;

export const WorldEvent = __t.object("WorldEvent", {
  id: __t.u64(),
  year: __t.f32(),
  createdAt: __t.timestamp(),
  actorName: __t.string(),
  text: __t.string(),
});
export type WorldEvent = __Infer<typeof WorldEvent>;

// The tagged union or sum type for the algebraic type `WorldStatus`.
export const WorldStatus = __t.enum("WorldStatus", {
  Lobby: __t.unit(),
  Running: __t.unit(),
  Ended: __t.unit(),
});
export type WorldStatus = __Infer<typeof WorldStatus>;

