// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import ClaimNationReducer from "../claim_nation_reducer";
import InvestEducationReducer from "../invest_education_reducer";
import ProposeTradeReducer from "../propose_trade_reducer";
import ResetGameReducer from "../reset_game_reducer";
import RespondTradeReducer from "../respond_trade_reducer";
import SetTaxReducer from "../set_tax_reducer";
import StartRunReducer from "../start_run_reducer";

export type ClaimNationParams = __Infer<typeof ClaimNationReducer>;
export type InvestEducationParams = __Infer<typeof InvestEducationReducer>;
export type ProposeTradeParams = __Infer<typeof ProposeTradeReducer>;
export type ResetGameParams = __Infer<typeof ResetGameReducer>;
export type RespondTradeParams = __Infer<typeof RespondTradeReducer>;
export type SetTaxParams = __Infer<typeof SetTaxReducer>;
export type StartRunParams = __Infer<typeof StartRunReducer>;

